
stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: python:3.12-slim-bullseye
  before_script:
    - apt-get update && apt-get install make
  script:
    - pip install -r requirements.txt
    - python -m pytest

