run_tess:
  before_script:
    - echo "Preparing test data..."
  script:
    - echo "Running tests..."
  after_script:
    - echo "Cleaning up temporary files... "
build_image:
  script:
    - echo "Building the docker image..."
    - echo "Tagging the docker image..."
push_image:
  script:
    - echo "Loggin into docker registry"
    - echo "Pushing image into docker registry"