variables: 
  IMAGE_NAME: amrmaro/demo-app
  IMAGE_TAG: python-app-1.0

# I love CI/CD
stages:
  - test
  
# Job 1
run_tests:
  stage: test
  image: python:3.9.14-slim-bullseye
  before_script:
    - apt-get update && apt-get install make
  script:
    - make test



  
