run_tests:
  stage: test
  image: python:3.9-slim-buster
  before_script:
    - apt-get update && apt-get install make
  script:
    - make test

build_image:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u REGISTRY_USER -p REGISTRY_PASS
  script:
    - docker build -t hiteshdev47/python-app-gitlab:app-v1 .
    - docker push hiteshdev47/python-app-gitlab:app-v1
