variables:
  IMAGE_NAME: ${REGISTRY_USER}/demo-app
  IMAGE_TAG: python-app-1.0

run_test:
  image: python:3.9-slim-bookworm
  before_script:
    - apt-get update && apt-get install make
  script: 
    - make test

build_image:
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER --password-stdin $REGISTRY_PASSWORD
  script:
    - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
    - docker push ${IMAGE_NAME}:${IMAGE_TAG}

