variables: 
  IMAGE_NAME: amrmaro/demo-app
  IMAGE_TAG: python-app-1.0

# I love CI/CD
stages:
  - test
  - build

# Job 1
run_tests:
  stage: test
  image: python:3.9.14-slim-bullseye
  before_script:
    - apt-get update && apt-get install make
  script:
    - make test

# Job 2
build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables: 
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

  
