variables:
  IMAGE_NAME: "$REGISTRY_USER/demo-app"
  IMAGE_TAG: python-app-1.1
  IMAGE_NAME_TAG: ${IMAGE_NAME}:${IMAGE_TAG}

stages:
  - test
  - build
  - deploy

# run_test:
#   stage: test
#   image: python:3.9-slim-bookworm
#   before_script:
#     - apt-get update && apt-get install make
#   script: 
#     - make test

# build_image:
#   stage: build
#   image: docker:24.0.7
#   services:
#     - docker:24.0.7-dind
#   variables:
#     DOCKER_TLS_CERTDIR: "/certs"
#   before_script:
#     - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin
#   script:
#     - docker build -t $IMAGE_NAME_TAG .
#     - docker push $IMAGE_NAME_TAG

deploy:
  stage: deploy
  image: ubuntu:20.04
  before_script:
    - apt-get update -y
    - apt-get install -y openssh-client
    - apt-get install -y sshpass
  script:
    - sshpass -p $SSH_PASS ssh -o StrictHostKeyChecking=no $SSH_USER@$VM_IPADDRESS "echo Metallica > file.txt"

