run_test:
  image: python:3.9-slim-buster
  before_script:
    - apt-get update && apt-get install -y make
  script:
    - pip install --upgrade pip setuptools
    - pip install -r requirements.txt  # Install your project dependencies
    - make test
