# Reference configuration example from https://www.youtube.com/watch?v=qP8kir2GUgo (GitLab Tutorial for Beginners)
run_tests:
  stage: test
  image: python:3.9-slim-buster
  before_script:
    - apt-get update && apt-get install make
  script:
    - make test

build_image:
  image: docker:24.0
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/cert"
  variables:
    IMAGE_NAME: techguyblogwaites/gitlab
    IMAGE_TAG: python-app-1.0
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG


