# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test
- build
- deploy
run_tests:
  stage: test
  image: python:3.9-slim-buster
  before_script:
  - apt-get update && apt-get install make
  script:
  - make test
build_image:
  stage: build
  image: docker:24.0
  services:
  - docker:24-dind
  variables:
    IMAGE_NAME: techguyblogwaites/gitlab
    IMAGE_TAG: python-app-1.0
  before_script:
  - "$IMAGE_NAME:$IMAGE_TAG"
  script:
  - docker build -t $IMAGE_NAME:$IMAGE_TAG .
  - docker push $IMAGE_NAME:$IMAGE_TAG
deploy:
  stage: deploy
  before_script:
  - chmod 400 $SSH_KEY
  script:
  - ssh -o StrictHostChecking=no -i $SSH_KEY unitedcyberxps@192.168.49.1 " docker
    login -u $REGISTRY_USER -p $REGISTRY_PASS && docker ps -aq | xargs docker stop
    | xargs docker rm && docker run -d -p 5001:5001 $IMAGE_NAME:$IMAGE_TAG"
include:
- template: Auto-DevOps.gitlab-ci.yml
