
stages:
  - test
  - build
  
run_tests:
  stage: test
  image: python:3.9-slim-buster
  script:
    - echo "some test"

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u "gerrome" -p $REGISTRY_PASS "gerrome6354"
  script:
    - docker build -t testimage:latest
    - docker push testimage:latest
